[general]
access-control-allow-origin="*"

[logging]
level="info"

[zookeeper]
servers=[{ZOOKEEPER_SERVERS}]

[client-profile.kafka-profile]
kafka-version="{KAFKA_VERSION}"
client-id="burrow-client"

[cluster.gw]
class-name="kafka"
client-profile="kafka-profile"
servers=[{KAFKA_BROKERS}]
topic-refresh=120
offset-refresh=10

[consumer.consumer_kafka]
class-name="kafka"
cluster="gw"
servers=[{KAFKA_BROKERS}]
client-profile="kafka-profile"
start-latest=false
offsets-topic="__consumer_offsets"
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"

[consumer.consumer_zk]
class-name="kafka_zk"
cluster="gw"
servers=[{ZOOKEEPER_SERVERS}]
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"

[notifier.influxdb]
class-name="http"
interval=10
threshold=1
send-close=false
template-open="/etc/burrow/tmpl/http-influxdb.tmpl"
url-open="{INFLUXDB_URL}"

[httpserver.default]
address=":8000"