[general]
access-control-allow-origin="*"

[logging]
level="info"

[zookeeper]
servers=[{ZOOKEEPER_SERVERS}]

[client-profile.kafka10]
kafka-version="0.10.1.0"
client-id="burrow-client"

[cluster.gw]
class-name="kafka"
client-profile="kafka10"
servers=[KAFKA_BROKERS]
topic-refresh=120
offset-refresh=10

[consumer.consumer_kafka]
class-name="kafka"
cluster="gw"
servers=[KAFKA_BROKERS]
client-profile="kafka10"
start-latest=false
offsets-topic="__consumer_offsets"
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"

[consumer.consumer_zk]
class-name="kafka_zk"
cluster="gw"
servers=[{ZOOKEEPER_SERVERS}]
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"

[httpserver.default]
address=":8000"
